-- =====================================================================
-- AI OUTCOME LEDGER — claims corpus (81 rows)
-- Run this FOURTH. Re-runnable: keyed on claims.ref.
--
-- Coding rules live in docs/METHODOLOGY.md. Short version:
--   measurement_basis  = what the number IS, not what it was called
--   destination        = where the gain landed (0..5)
--   traceable_to_pl_usd = how much can be tied to a disclosed P&L line.
--                         Default 0. Only non-zero with a named line item.
--   epistemic_tag      = fact | strong | inference | speculation | unknown
--   evidence_tier      = 1 primary | 2 vendor/self-originated | 3 press
--
-- source_url is null wherever a stable canonical URL was not confirmed.
-- verify_hint carries the exact next step instead. The app turns those
-- into one-click EDGAR full-text and Scholar searches. Nothing here was
-- given a URL from memory.
-- =====================================================================

with src (
  ref, company_slug, counterparty_slug, claim_date, period_label, headline, claim_detail,
  claimed_amount_usd, claimed_value, claimed_unit, measurement_basis, measurement_definition,
  destination, destination_rationale, counterparty_absorbed, transfer_amount_usd, counterparty_note,
  traceable_to_pl_usd, reconciliation_note, observed_counter_move,
  cond_bu, cond_ds, cond_pa, conditions_note,
  epistemic_tag, evidence_tier, conflict_of_interest, coi_note,
  verification_status, verify_hint, source_type, source_name, source_date
) as (values

-- =========================== IBM =====================================
('ibm-productivity-3-5b-2024','ibm',null,'2024-12-31'::date,'FY2024',
 'IBM reports $3.5B of productivity savings in 2024 against a $2B target',
 'Headline internal-transformation figure, roughly $4.5B cumulative over two years. Presented as productivity, not as cost removed.',
 3500000000::numeric,3.5::numeric,'usd','gross_capacity',
 'Hours freed across functions, valued at loaded cost. Not traceable to a P&L line because the capacity was redeployed rather than removed. IBM states this openly.',
 1::smallint,'Capacity was redeployed into engineering, sales and marketing. Nothing left the cost base.',
 false,null::numeric,null,
 0::numeric,'No line item corresponds to this figure. Treat any board deck that quotes it as $3.5B of cost taken out as a category error.',
 'Total headcount rose over the same period.',
 true,true,true,'Software and services pricing survives; redeployment is a demand sink; no external permission needed for internal functions.',
 'fact',2::smallint,true,'IBM sells the AI products this figure validates.',
 'secondary_only','Confirm in the FY2024 annual report and the investor-day deck. EDGAR full text: "productivity" within IBM 10-K FY2024.',
 'press_release','IBM investor communications','2025-01-29'::date),

('ibm-askhr-94pct','ibm',null,'2024-12-31','FY2024',
 'AskHR automates 94% of routine HR inquiries across 11.5M interactions',
 'About 90 embedded automations. Managers complete HR transactions roughly 75% faster. HR NPS moved from -35 to +74.',
 null,94,'pct','activity',
 'Share of inquiries resolved without a human. An activity ratio, not a cost measure.',
 1,'Freed HR capacity was absorbed internally.',false,null,null,
 0,'No dollar figure attached at this level.',null,
 true,true,true,null,
 'fact',2,true,'Self-reported and used as sales collateral.',
 'secondary_only','IBM Institute / newsroom HR case study. Cross-check the NPS movement, which is the least plausible number in the set.',
 'press_release','IBM newsroom','2025-01-29'),

('ibm-askit-70pct','ibm',null,'2024-12-31','FY2024',
 'AskIT reduces IT calls and chats by 70%',null,
 null,70,'pct','activity','Volume reduction in support contacts.',
 1,null,false,null,null,0,null,null,
 true,true,true,null,'fact',2,true,null,
 'secondary_only','Same IBM Client Zero materials as AskHR.','press_release','IBM newsroom','2025-01-29'),

('ibm-support-165m','ibm',null,'2025-12-31','since 2022',
 'IBM claims $165M of operational savings in customer support since 2022',
 '70% of inquiries resolved by a digital assistant. Resolution time on complex issues improved 26%. CSAT up 25 points.',
 165000000,165,'usd','unverified',
 'The source does not state whether this is cost removed from a line or capacity valued at loaded cost. Until that is resolved the basis cannot be coded.',
 0,'Uncodable until the measurement definition is established.',false,null,null,
 0,'Unreconciled by default because the basis is unknown, not because it is disputed.',null,
 true,true,true,null,'strong',2,true,null,
 'needs_primary_source','Ask IBM IR directly whether the $165M is gross capacity or a reduction in support opex. This single question re-codes the row.',
 'press_release','IBM newsroom','2026-01-28'),

('ibm-apptio-600m','ibm',null,'2025-12-31','since 2022',
 'IBM reports roughly $600M of enterprise IT cost savings since 2022 via IT modernisation',null,
 600000000,600,'usd','net_pl',
 'IT spend reduction. Closer to a real cost line than the productivity figure, but not separately disclosed.',
 5,'IT infrastructure spend is a line a firm can actually remove.',false,null,null,
 0,'Not separately disclosed in financial statements.',null,
 true,true,true,null,'strong',2,true,null,
 'needs_primary_source','Check whether IBM total expense and other income shows a matching movement over the same window.',
 'press_release','IBM newsroom','2026-01-28'),

('ibm-hr-opex-40pct','ibm',null,'2025-12-31','4 years',
 'IBM reports a 40% reduction in HR team operational costs over four years',null,
 null,40,'pct','net_pl','Functional operating cost reduction.',
 5,'Function-level restructuring, which is the kind of change Census data associates with actual headcount reduction.',
 false,null,null,0,null,null,
 true,true,true,null,'strong',2,true,null,
 'needs_primary_source','Get the denominator. 40% of what base, and over which four years.',
 'press_release','IBM newsroom','2026-01-28'),

('ibm-headcount-rose','ibm',null,'2025-12-31','FY2024-25',
 'IBM headcount rose while AI savings were being reported',
 'Krishna has described redeploying freed capacity into engineers, sales and marketing rather than removing it.',
 null,null,null,'headcount',
 'Total employees. The counter-observation to the productivity figure.',
 1,'This is the direct evidence that the productivity number is capacity, not cost.',
 false,null,null,0,null,
 'Savings claimed and headcount up in the same period.',
 true,true,true,null,'fact',1,false,null,
 'verified_primary','Employee counts appear in the IBM 10-K. Confirm the exact figures per year.',
 'sec_filing','IBM Form 10-K','2026-02-24'),

-- ======================== ServiceNow =================================
('servicenow-now-on-now-500m','servicenow',null,'2026-03-31','FY2026',
 'ServiceNow reports $0.5B captured internally through "Now on Now"',null,
 500000000,0.5,'usd','gross_capacity',
 'Described as productivity captured. Same definitional problem as IBM.',
 1,null,false,null,null,0,
 'Non-GAAP operating margin around 32%, consistent with prior trend.',null,
 true,true,true,null,'fact',2,true,'The internal deployment is the sales collateral.',
 'secondary_only','ServiceNow investor materials. Ask whether the $0.5B is in the opex bridge.',
 'press_release','ServiceNow investor relations','2026-01-28'),

('servicenow-ai-acv-1b','servicenow',null,'2026-06-30','Q2 FY2026',
 'ServiceNow AI annual contract value crosses $1B; internal 2026 target raised to $1.5B',
 'Seller-side revenue, not a buyer-side saving. Included to size the other end of the transfer.',
 1000000000,1,'usd','net_pl','AI-attributed annual contract value. Revenue.',
 0,'Vendor revenue. The five destinations describe buyer-side gains and do not apply.',
 false,null,null,1000000000,'Revenue is disclosed and auditable.',null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Quarterly earnings release and call transcript.','earnings_call','ServiceNow Q2 FY2026','2026-07-23'),

-- ========================= Salesforce ================================
('salesforce-4000-support-roles','salesforce',null,'2025-09-30','Sep 2025',
 'Salesforce cuts about 4,000 customer support roles, attributed to AI agents',
 'Further reductions followed in January and June 2026.',
 null,4000,'fte','headcount','Roles removed, AI-attributed by management.',
 5,'Claimed as a margin action.',false,null,null,
 0,'The reduction is real. The margin effect is not visible.',
 'GAAP operating margin 21.3% to 21.1%; non-GAAP 35.5% to 34.8% across the following quarters.',
 false,true,true,'Per-seat pricing means the billing unit does not survive the automation. Fails condition 1.',
 'fact',3,false,null,
 'secondary_only','Confirm against 10-Q headcount disclosure and any 8-K restructuring charge.',
 'press','Reported September 2025','2025-09-02'),

('salesforce-margin-did-not-expand','salesforce',null,'2026-04-30','Q1 FY27',
 'Three rounds of AI-attributed headcount reduction and operating margin did not expand',
 'GAAP 21.3% (Q3 FY26) to 21.1% (Q1 FY27). Non-GAAP 35.5% to 34.8%. The Informatica acquisition confounds the comparison because acquired revenue carries different margins.',
 null,-20,'bps','net_pl','Reported operating margin, GAAP and non-GAAP.',
 1,'The savings did not reach margin. Where they went is not disclosed.',
 false,null,null,0,null,
 'This is itself the counter-move to the three preceding headcount claims.',
 false,true,true,null,'fact',1,false,null,
 'verified_primary','Both figures are in the quarterly earnings releases. Suggestive, not conclusive, because of Informatica.',
 'sec_filing','Salesforce Form 10-Q','2026-05-28'),

('salesforce-agentforce-arr','salesforce',null,'2026-04-30','Q1 FY27',
 'Agentforce ARR reaches $1.2B, up 205% year over year',null,
 1200000000,205,'pct','net_pl','Annual recurring revenue. Seller side.',
 0,'Vendor revenue.',false,null,null,1200000000,null,
 'The stock fell roughly 28% over the period as the market priced seat erosion faster than AI revenue.',
 null,null,null,'Being the vendor of the disruption does not exempt you from it.',
 'fact',1,false,null,'verified_primary','Earnings release.','earnings_call','Salesforce Q1 FY27','2026-05-28'),

('salesforce-help-portal-75pct','salesforce',null,'2026-01-31','FY2026',
 'Internal help portal resolves 75% of 1M+ annual conversations without escalation',null,
 null,75,'pct','activity','Deflection rate.',1,null,false,null,null,0,null,null,
 null,null,null,null,'fact',2,true,null,'secondary_only','Salesforce internal-deployment blog posts.','press_release','Salesforce','2026-01-31'),

('salesforce-agentforce-2usd','salesforce',null,'2026-01-31','2026',
 'Agentforce priced at $2.00 per conversation',
 'Against a $30-50 human interaction cost.',
 null,2,'usd','unit_economics','Price per unit of output, not per seat.',
 4,'Value passed to the buyer through price. This is pass-through, not capture.',
 false,null,null,null,null,null,
 true,null,null,'Repricing to an output unit is the condition-1 fix.',
 'fact',2,true,null,'secondary_only','Public pricing page. Re-check quarterly; these prices are falling.',
 'vendor_report','Salesforce pricing','2026-01-31'),

-- ========================== Microsoft ================================
('microsoft-call-center-500m','microsoft',null,'2025-07-31','2025',
 'Microsoft executive cites around $500M saved in call centres in one year',
 'Stated in the same year as substantial layoffs. The relationship between the two was not disclosed.',
 500000000,500,'usd','unverified',
 'Not defined in the source. Could be deflected contacts valued at cost, or vendor spend removed.',
 0,'Uncodable without a definition. If it is outsourced contact-centre spend, it is destination 3.',
 null,null,'If this is BPO spend removed, a named supplier lost the revenue. Worth establishing.',
 0,null,null,null,null,null,null,
 'strong',3,true,null,
 'needs_primary_source','Find the original remark and whether it refers to internal cost or vendor spend. This determines destination 3 vs 5.',
 'press','Reported July 2025','2025-07-09'),

-- ========================== JPMorgan =================================
('jpm-2b-benefit-2b-cost','jpmorgan',null,'2025-10-31','2025',
 'JPMorgan: about $2B of AI benefit against about $2B of AI expense',
 'Dimon on Bloomberg TV, October 2025. Roughly $2B per year of AI spend inside an $18B technology budget. 200,000+ employees on the internal LLM suite.',
 2000000000,2,'usd','net_pl',
 'Described as actual cost saves. Gross benefit is around 1.1% of 2025 revenue of $185.6B.',
 5,'Claimed as margin, but the net contribution to EBIT is approximately zero once the cost is netted.',
 false,null,null,
 0,'Benefit and cost stated as equal. The best-resourced AI program in global finance reports break-even.',
 'Net EBIT contribution approximately zero on the companys own numbers.',
 true,true,false,'Permission to act is constrained by regulation; the bank is not free to remove controls.',
 'fact',3,false,null,
 'secondary_only','Locate the exact interview transcript and any repetition of the figure in the 10-K MD&A.',
 'interview','Bloomberg TV','2025-10-13'),

('jpm-ops-productivity-25pct','jpmorgan',null,'2025-12-31','FY2025',
 'Accounts handled per operations staffer up about 25%',null,
 null,25,'pct','time','Throughput per worker. Capacity, not cost.',
 1,null,false,null,null,0,null,null,
 true,true,false,null,'fact',2,false,null,
 'secondary_only','Investor day materials.','press_release','JPMorgan investor day','2026-05-19'),

('jpm-inbound-calls-30pct','jpmorgan',null,'2025-12-31','FY2025',
 'Inbound calls per account down about 30%',null,
 null,30,'pct','activity','Contact volume per account.',1,null,false,null,null,0,null,null,
 true,true,false,null,'fact',2,false,null,'secondary_only','Investor day materials.','press_release','JPMorgan investor day','2026-05-19'),

('jpm-ai-spend-2b','jpmorgan',null,'2026-01-31','FY2026',
 'About $2B per year of AI spend inside a $19.8B technology budget',
 'Roughly 2,000 AI/ML staff, 100+ generative AI solutions in production, AI work dating to 2012.',
 2000000000,2,'usd','net_pl','Spend, not saving. The denominator for every benefit claim above.',
 0,'Cost side.',false,null,null,2000000000,'Disclosed spend.',null,
 null,null,null,null,'fact',2,false,null,
 'secondary_only','Technology budget appears in investor day materials.','press_release','JPMorgan investor day','2026-05-19'),

-- ============================ Klarna =================================
('klarna-700-agents-2024','klarna',null,'2024-02-27','Feb 2024',
 'Klarna AI assistant handles 2.3M chats a month, described as the work of 700 full-time agents',
 'Projected roughly $40M of profit improvement for 2024.',
 40000000,700,'fte','gross_capacity',
 'Headcount equivalence derived from chat volume. A capacity translation, not a cost line.',
 1,'The projection was not subsequently reconciled to a cost line.',
 false,null,null,0,
 'The $40M projection has no published outturn.',null,
 false,true,false,null,'fact',2,true,'Published during a pre-IPO period.',
 'secondary_only','Klarna press release, February 2024. Then look for any restatement in the F-1.',
 'press_release','Klarna','2024-02-27'),

('klarna-headcount-f1','klarna',null,'2025-08-31','FY2022-24',
 'Klarna F-1: headcount falls from 5,527 to 4,352 to 3,422',
 'The filing attributes this to a strategic decision to reduce headcount and drive efficiency by leveraging AI, and states it expected further decreases.',
 null,-2105,'fte','headcount','Employee counts in a registration statement. Audited context.',
 5,'Claimed as an efficiency outcome.',false,null,null,0,null,null,
 false,true,false,null,'fact',1,false,null,
 'verified_primary','Form F-1 and amendments, SEC 2025.','sec_filing','Klarna Group plc Form F-1','2025-08-14'),

('klarna-60m-saved-cost-rose','klarna',null,'2025-11-30','Q3 2025',
 'Klarna reports $60M saved by the AI agent while customer service and operations cost rose 19%',
 'The AI agent was said to be doing the work of 853 employees. In the same quarter the customer service and operations line was $50M, up from $42M a year earlier.',
 60000000,60,'usd','gross_capacity',
 'Savings computed as avoided labour at loaded cost. The cost line it should have reduced went the other way.',
 1,'Consumed by volume growth, quality remediation and rehiring before reaching the P&L.',
 false,null,null,
 0,'The single cleanest instance in the corpus of a verified saving that never lands. Both numbers come from the same earnings call.',
 'Customer service and operations cost rose to $50M from $42M year over year, up 19%.',
 false,false,false,'Fails all three conditions in the same quarter.',
 'fact',1,false,null,
 'verified_primary','Q3 2025 earnings call and quarterly report. Both figures are in the same disclosure, which is what makes this row usable.',
 'earnings_call','Klarna Q3 2025','2025-11-18'),

('klarna-quality-reversal','klarna',null,'2025-05-31','May 2025',
 'Klarna says it went too far on cost and quality suffered; rehiring begins',
 'Siemiatkowski to Bloomberg. Rehiring for premium and complex-case tiers under a remote contractor model.',
 null,null,null,'quality','Service quality, stated qualitatively by the CEO.',
 2,'The gain was partly returned as a quality correction.',
 false,null,null,0,null,
 'Directly precedes the Q3 disclosure in which the cost line rises.',
 false,false,false,null,'fact',3,false,null,
 'secondary_only','Bloomberg interview, May 2025.','interview','Bloomberg','2025-05-08'),

('klarna-marketing-7m-quarter','klarna',null,'2025-11-30','Q3 2025',
 'Klarna reports about $7M per quarter of marketing savings from AI-driven CRM — and this one shows up',
 'An input-cost reduction in a line the firm controls, rather than a labour-capacity translation.',
 28000000,7,'usd','net_pl',
 'Marketing spend reduction, annualised from a quarterly figure.',
 5,'Retained as margin. The contrast case to the $60M row above.',
 false,null,null,
 28000000,'Traceable because marketing spend is a disclosed line the firm directly controls.',null,
 true,true,true,'Passes all three: the billing unit is unaffected, the saving is an input cost, and no external permission is required.',
 'fact',1,false,null,
 'verified_primary','Same quarterly disclosure as the $60M claim.','earnings_call','Klarna Q3 2025','2025-11-18'),

-- ============================= WTW ===================================
('wtw-propel-400m','wtw',null,'2026-01-31','to 2028',
 'WTW targets $400M of run-rate savings by 2028 for about $625M of cash investment',null,
 400000000,400,'usd','net_pl','Run-rate savings target with a disclosed investment denominator.',
 5,null,false,null,null,
 350000000,'WTW itself states that $50M of the $400M is earmarked for reinvestment and will not reach the bottom line.',null,
 true,true,true,null,'fact',1,false,null,
 'verified_primary','Propel AI Acceleration Plan disclosure in quarterly materials.','earnings_call','WTW','2026-02-03'),

('wtw-reinvestment-leakage','wtw',null,'2026-01-31','to 2028',
 'WTW publishes the reinvestment leakage as a line item: $350M net of $50M reinvested',
 'Almost nobody else does this. It is the honest version of what happens invisibly everywhere else in this ledger.',
 50000000,50,'usd','net_pl','Gross savings less explicitly earmarked reinvestment.',
 5,'Named as the portion that will not reach EBIT.',
 false,null,null,50000000,
 'Fully reconciled by construction: the company disclosed the gap rather than leaving it to be discovered.',null,
 true,true,true,null,'fact',1,false,null,
 'verified_primary','Same disclosure. Use this row as the template for what you want other firms to publish.',
 'earnings_call','WTW','2026-02-03'),

('wtw-margin-1950','wtw',null,'2026-06-30','Q2 2026',
 'WTW adjusted operating margin 19.5%, up 100bps, against a 2028 target near 30%',null,
 null,19.5,'pct','net_pl','Adjusted operating margin.',5,null,false,null,null,0,null,null,
 true,true,true,null,'fact',1,false,null,'verified_primary','Quarterly earnings release.','earnings_call','WTW Q2 2026','2026-07-30'),

-- =========================== Verizon =================================
('verizon-ebitda-389','verizon',null,'2026-03-31','Q1 2026',
 'Verizon posts a record 38.9% adjusted EBITDA margin, up 140bps, with AI cited among the causes',
 'Management attributes the expansion in the same breath to churn improvement, reduced acquisition and retention spend, and a 27% drop in upgrade volumes.',
 null,140,'bps','net_pl','Adjusted EBITDA margin. Real, disclosed, and unattributable.',
 0,'Nobody knows how much is AI, including Verizon. This is the normal case, not the exception.',
 false,null,null,0,
 'No attribution is possible. When a survey asks a CFO what share of EBIT is attributable to AI, this is the epistemic position they answer from.',null,
 true,true,true,null,'fact',1,false,null,
 'verified_primary','Q1 2026 earnings release and call.','earnings_call','Verizon Q1 2026','2026-04-21'),

('verizon-opex-5b-target','verizon',null,'2026-01-31','FY2026',
 'Verizon targets $5B of operating expense savings in 2026 with AI embedded in the program',null,
 5000000000,5,'usd','net_pl','Cost program target, not AI-specific.',
 0,'AI is one input to a multi-cause program.',false,null,null,0,null,null,
 true,true,true,null,'fact',1,false,null,'verified_primary','Investor materials.','earnings_call','Verizon','2026-01-27'),

-- ============================ Lumen ==================================
('lumen-copilot-50m','lumen',null,'2025-06-30','2025',
 'Lumen reports roughly $50M of annual value from Copilot in the sales organisation',
 'Framed as hours returned to sellers, converted to a dollar figure.',
 50000000,50,'usd','gross_capacity',
 'Seller hours saved, valued at loaded cost. Capacity, not cost removed.',
 1,'Unless the freed selling time converts to bookings, this is slack.',
 false,null,null,0,null,null,
 true,true,true,'Selling capacity has a natural demand sink if pipeline exists.',
 'strong',3,true,'Figure originates in vendor case-study material.',
 'needs_primary_source','Find whether Lumen repeats the figure in its own filings or only in Microsoft case studies. The distinction matters.',
 'vendor_report','Microsoft customer story','2025-06-30'),

-- =========================== Amazon ==================================
('amazon-corporate-reductions-2025','amazon',null,'2025-10-31','Oct 2025',
 'Amazon announces large corporate role reductions alongside AI-first internal messaging',
 'Reported figures vary across outlets and the AI-attributable share was not disclosed.',
 null,null,'fte','headcount','Announced role reductions. AI share undisclosed.',
 0,'No AI attribution was published, so destination cannot be coded.',
 false,null,null,0,null,null,
 null,null,null,null,'strong',3,false,null,
 'needs_primary_source','Get the exact announced figure from the Amazon press release or 8-K rather than from press aggregation. Do not carry a number into the ledger until then.',
 'press','Reported October 2025','2025-10-28'),

('shopify-ai-hiring-gate','shopify',null,'2025-04-30','Apr 2025',
 'Shopify requires teams to show AI cannot do the work before requesting headcount',
 'A permission-to-act datapoint rather than a savings claim: it changes who is allowed to convert capacity into a decision.',
 null,null,null,'headcount','Policy, not a measurement.',
 0,'Not a gain claim.',false,null,null,0,null,null,
 null,null,true,'This is condition 3 being deliberately engineered.',
 'fact',3,false,null,
 'secondary_only','CEO memo, published publicly April 2025.','press','Public memo','2025-04-07'),

-- ===================== Commonwealth Bank =============================
('cba-call-volume-claim','cba',null,'2025-07-31','2025',
 'CBA cites a large reduction in call volumes from an AI voice bot to support role cuts',null,
 null,30,'pct','activity','Call volume reduction.',5,'Used to justify a headcount action.',
 false,null,null,0,null,
 'The bank subsequently reversed the associated role cuts.',
 null,null,false,null,'strong',3,false,null,
 'needs_primary_source','Confirm the exact percentage claimed and the date. Reported figures differ across outlets.',
 'press','Reported 2025','2025-07-15'),

('cba-reverses-cuts','cba',null,'2025-08-31','Aug 2025',
 'CBA reverses AI-attributed role cuts after the underlying call-volume claim is challenged',
 'A Klarna-shaped correction on a compressed timeline: the claim did not survive contact with the counter-evidence.',
 null,45,'fte','headcount','Roles reinstated.',
 2,'The gain was returned as a service-quality and industrial-relations correction.',
 false,null,null,0,null,
 'Directly contradicts the preceding claim by the same institution within about a month.',
 null,false,false,null,'strong',3,false,null,
 'needs_primary_source','Find the bank statement and the union submission. Both are public. This is one of the few cases with an adversarial document available.',
 'press','Reported August 2025','2025-08-21'),

('duolingo-ai-first-walkback','duolingo',null,'2025-05-31','2025',
 'Duolingo announces an AI-first contractor policy and then publicly walks it back',
 'Included as a reputational-cost datapoint. No savings figure was ever published.',
 null,null,null,'quality','No measurement published.',
 0,null,false,null,null,0,null,null,
 null,null,false,null,'strong',3,false,null,
 'secondary_only','CEO posts, April and May 2025.','press','Public statements','2025-05-01'),

-- ========================== Accenture ================================
('accenture-ai-bookings-11-5b','accenture',null,'2026-01-31','Q1 FY2026',
 'Accenture reports $11.5B cumulative advanced-AI bookings and $4.8B cumulative revenue',
 'Q1 FY2026 alone: $2.2B bookings up 76%, about $1.1B revenue up 120%, across 1,300+ clients and 11,000 projects.',
 11500000000,11.5,'usd','net_pl','Bookings and revenue. Seller side.',
 0,'Vendor revenue. Note the 42% bookings-to-revenue conversion, which implies long cycles and a large gap between commitment and delivered work.',
 false,null,null,4800000000,'Revenue is disclosed and audited.',null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Form 10-Q FY2026 Q1 and the earnings call.','sec_filing','Accenture Form 10-Q','2026-01-31'),

('accenture-own-economics','accenture',null,'2026-03-31','FY2026',
 'The largest implementer of enterprise AI grows 3-5% at about 14% operating margin',
 'FY2025 revenue $69.7B up 7%, new bookings $80.6B down 1%, about 799,000 people. Q2 FY2026 operating margin 13.8% versus 13.5%.',
 null,13.8,'pct','net_pl','Reported operating margin.',
 0,'Whatever value 11,000 projects create, the implementer is not capturing much of it either.',
 false,null,null,0,null,
 'Bookings declined in the year the AI bookings figure was being publicised.',
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Form 10-Q FY2026 Q2 and FY2025 results.','sec_filing','Accenture Form 10-Q','2026-03-31'),

-- ===================== BPO: where the gains land =====================
('isg-bpo-acv-minus-14','isg','concentrix','2025-12-31','FY2025',
 'BPO annual contract value falls 14% in 2025, the lowest level since 2020',
 'The measured aggregate of the transfer. Every buyer-side saving from eliminating outsourced work appears here as a revenue decline.',
 null,-14,'pct','net_pl','Contract value across the tracked BPO market.',
 3,'This is the destination-3 total, observed from the receiving end.',
 true,null,'Sector-wide rather than a single named counterparty.',
 0,null,null,
 false,null,null,null,'strong',2,false,'Industry research firm with vendor relationships.',
 'secondary_only','ISG Index quarterly releases. Confirm the exact 2025 figure and the comparison base.',
 'industry_survey','ISG Index','2026-01-15'),

('nanda-bpo-elimination-2-10m','mit-nanda',null,'2025-07-31','2025',
 'Documented back-office ROI comes from BPO elimination of $2-10M annually, without material internal workforce reduction',
 'Also 30% reductions in external creative and content spend, and about $1M a year on outsourced risk management at financial services firms. The ROI came from cutting external spend.',
 null,null,'usd','net_pl',
 'External spend removed. A real cost line, and simultaneously somebody elses revenue line.',
 3,'The buyer gain equals a supplier loss. In national accounts it nets to roughly zero.',
 true,null,'Counterparty is the outsourcing sector generally.',
 0,'Range deliberately not averaged. $2-10M is a range, and collapsing it to $6M would invent precision the source does not have.',null,
 false,null,null,null,'strong',2,false,null,
 'secondary_only','MIT Project NANDA, The GenAI Divide, July 2025.','vendor_report','MIT Project NANDA','2025-07-31'),

('teleperformance-fy2025-loss','teleperformance',null,'2026-02-28','FY2025',
 'Teleperformance reports a net loss of $1.28B, driven by a $1.52B non-cash goodwill impairment',
 'An impairment is the accounting system recognising that expected future cash flows have fallen. This is the transfer showing up on the receiving side.',
 1280000000,-1.28,'usd','net_pl','Reported net loss and impairment charge.',
 3,'The receiving end of buyer-side AI savings.',
 true,1520000000,'Teleperformance is the counterparty in this row rather than the claimant.',
 1520000000,'Fully disclosed in audited statements.',null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','FY2025 annual results. Not an SEC filer, so fundamentals must be entered manually.',
 'press_release','Teleperformance FY2025 results','2026-02-26'),

('teleperformance-q1-2026','teleperformance',null,'2026-04-30','Q1 2026',
 'Teleperformance revenue down 2.2% like-for-like; Trust and Safety declining as automation handles routine moderation',null,
 null,-2.2,'pct','net_pl','Like-for-like revenue growth.',3,null,
 true,null,null,0,null,null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','Q1 2026 revenue release.','press_release','Teleperformance','2026-04-23'),

('concentrix-guidance-cut-130m','concentrix',null,'2026-06-30','Jun 2026',
 'Concentrix cuts the midpoint of FY2026 revenue guidance by about $130M; the stock falls around 24%',
 'Teleperformance fell as much as 16% to a decade low on the same news. One analyst described the sub-sector as uninvestable.',
 130000000,-130,'usd','net_pl','Guidance revision.',
 3,'The clearest single-day market recognition of the transfer.',
 true,130000000,null,130000000,'Guidance is company-issued and specific.',null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','Guidance revision, June 30 2026.','sec_filing','Concentrix 8-K / earnings release','2026-06-30'),

('concentrix-ceo-attribution','concentrix',null,'2026-06-30','Jun 2026',
 'Concentrix CEO attributes the shortfall to clients reallocating budget to their own AI, in some cases eliminating outsourced CX entirely',
 'Not reducing spend. Eliminating the function.',
 null,null,null,'unverified','Management attribution, qualitative.',
 3,'Names the mechanism explicitly from the receiving side, which is rare.',
 true,null,null,0,null,null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','Earnings call transcript, June 2026.','earnings_call','Concentrix','2026-06-30'),

-- ============================ Chegg ==================================
('chegg-opex-cut-33pct','chegg',null,'2025-08-31','Q2 2025',
 'Chegg cuts non-GAAP expenses 33% and delivers $23.1M of adjusted EBITDA while revenue falls 36%',
 'The AI efficiency program performed exactly as the pitch decks promise.',
 null,33,'pct','net_pl','Non-GAAP expense reduction and adjusted EBITDA.',
 5,'Retained as margin. And it did not matter, because the denominator collapsed.',
 false,null,null,23100000,'Reported in the quarterly financials.',
 'Revenue fell 36% in the same quarter. Efficiency is worthless when demand disappears.',
 false,false,true,'Passes condition 1 and 3, fails condition 2 catastrophically: the demand sink was annihilated.',
 'fact',1,false,null,
 'verified_primary','Form 10-Q Q2 2025 and Form 10-K FY2025.','sec_filing','Chegg Form 10-Q','2025-08-11'),

('chegg-revenue-collapse','chegg',null,'2025-08-31','Q2 2025',
 'Chegg revenue $105.1M, down 36%; subscription revenue down 39%; subscribers down 40% to 2.6M',
 'Non-subscriber traffic went from -8% in Q2 2024 to -49% in January 2025 as search AI overviews answered queries directly.',
 null,-36,'pct','net_pl','Reported revenue.',
 0,'Demand destruction, not a gain.',false,null,null,0,null,null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','Form 10-Q Q2 2025.','sec_filing','Chegg Form 10-Q','2025-08-11'),

('chegg-value-destruction','chegg',null,'2026-07-31','2021-2026',
 'Chegg loses about 99% of its market value in roughly 39 months',
 'From a $14.5B valuation and about $113 a share in 2021 to roughly $0.96 and a $125M market cap in July 2026. Kodak took a decade.',
 null,-99,'pct','net_pl','Market capitalisation.',
 0,'The terminal form of the demand-side risk.',false,null,null,0,null,null,
 false,false,true,null,'fact',1,false,null,
 'verified_primary','Price history is machine-verified by the price series in this app.','press','Market data','2026-07-31'),

-- ===================== Pricing and per-seat erosion ==================
('atlassian-seat-decline','atlassian',null,'2026-04-30','2026',
 'Atlassian reports its first ever decline in enterprise seat count',
 'The stock fell roughly 35%. Salesforce -28 to -30%, Workday -33% over comparable windows.',
 null,null,'ratio','net_pl','Seat count, the billing unit itself.',
 0,'Condition 1 failing in public.',false,null,null,0,null,null,
 false,null,null,'The billing unit did not survive the automation.',
 'fact',1,false,null,
 'verified_primary','Quarterly results and shareholder letter.','sec_filing','Atlassian','2026-04-30'),

('software-multiple-compression','atlassian',null,'2026-04-30','Jan-Apr 2026',
 'About $2 trillion of software market capitalisation evaporates between January and April 2026',
 'Roughly $285B in a 48-hour window in February. Software forward P/E fell below the overall market for the first time, from 84x at the 2021 peak to 22.7x.',
 2000000000000,-2,'usd','net_pl','Aggregate market capitalisation.',
 0,'Market-level repricing of the per-seat model.',false,null,null,0,null,null,
 false,null,null,null,'strong',3,false,null,
 'needs_primary_source','Reconstruct from index data rather than press aggregation before citing the $2T figure anywhere it matters.',
 'press','Market commentary','2026-04-30'),

('intercom-fin-099','intercom',null,'2026-01-31','2026',
 'Intercom Fin priced at $0.99 per resolution with a 76% average resolution rate',
 'Against a $30-50 human interaction cost.',
 null,0.99,'usd','unit_economics','Price per resolved outcome.',
 4,'The surplus is passed to the buyer through price. The seller does not keep it.',
 false,null,null,null,null,null,
 true,null,null,'Outcome pricing makes the unit legible and comparable, which accelerates price competition rather than protecting it.',
 'fact',2,true,null,'secondary_only','Public pricing page. Re-check quarterly.','vendor_report','Intercom pricing','2026-01-31'),

('hubspot-050-repricing','hubspot',null,'2026-04-30','Apr 2026',
 'HubSpot cuts its per-resolution price to $0.50',
 'The direction of travel on outcome pricing is down, fast. This is the pass-through happening in real time.',
 null,0.5,'usd','unit_economics','Price per resolution, after a cut.',
 4,'Pass-through, observed as a price cut rather than inferred.',
 false,null,null,null,null,null,
 true,null,null,null,'fact',2,true,null,
 'secondary_only','Public pricing page and the April 2026 change announcement.','vendor_report','HubSpot pricing','2026-04-30'),

('zendesk-verified-resolution','zendesk',null,'2026-01-31','2026',
 'Zendesk prices around $1.20-1.50 per verified resolution',null,
 null,1.35,'usd','unit_economics','Price per verified resolution. Range not averaged for analysis; midpoint stored only for sorting.',
 4,null,false,null,null,null,null,null,
 true,null,null,null,'fact',2,true,null,
 'secondary_only','Public pricing page.','vendor_report','Zendesk pricing','2026-01-31'),

('per-seat-pricing-collapse','mit-nanda',null,'2026-01-31','2025-26',
 'The share of SaaS companies pricing purely per seat falls from 21% to 15% in one year',
 'Gartner projects at least 40% of enterprise SaaS spend shifts to usage, agent or outcome pricing by 2030. IDC projects 70% of vendors leave pure per-seat by 2028.',
 null,-6,'pct','net_pl','Share of vendors on pure per-seat pricing.',
 4,'The structural migration away from the billing unit AI destroys.',
 false,null,null,0,null,null,
 false,null,null,'Condition 1 being repaired sector-wide.',
 'strong',2,false,null,
 'needs_primary_source','Pilot survey methodology and sample size. A 21 to 15 move needs a denominator before it carries weight.',
 'industry_survey','Pilot / Gartner / IDC','2026-01-31'),

-- ======================= AI-native greenfield ========================
('lovable-rpe','lovable',null,'2026-02-28','early 2026',
 'Lovable reports $400M ARR on 146 full-time employees, about $2.7M per employee',
 'Against a median private SaaS figure near $130K. The best-sourced revenue-per-employee figure in the AI-native group.',
 400000000,2700000,'usd','unit_economics','Annualised recurring revenue divided by headcount.',
 5,'AI-native economics, but by construction rather than by retrofit.',
 false,null,null,0,
 'Private company. ARR for consumption-priced products annualises a month that may not repeat.',null,
 true,true,true,'Satisfies all three conditions by construction, which is why the group looks like the answer and is not.',
 'fact',2,true,'Private company with active fundraising.',
 'secondary_only','TechCrunch report, company-confirmed. Note the ARR definition problem before using the multiple.',
 'press','TechCrunch','2026-02-01'),

('cursor-rpe-unusable','anysphere',null,'2026-05-31','2026',
 'Cursor revenue-per-employee cannot be computed: headcount is reported as 50, 150 and 300 in credible outlets in the same quarter',
 'ARR reported around $2B in February 2026 and $3B in May 2026. Any RPE figure spans a 6x range depending on which headcount you pick.',
 null,null,'ratio','unverified',
 'Not computable. The denominator is unknown by a factor of six.',
 0,'Uncodable.',false,null,null,0,
 'Do not use this figure in anything you need to defend. It is in the ledger specifically so that it stays flagged rather than quietly re-entering an argument.',null,
 true,true,true,null,'unknown',3,true,null,
 'disputed','Only a company-confirmed headcount resolves this. Until then the row stays unusable by design.',
 'press','Multiple outlets','2026-05-31'),

('midjourney-rpe-range','midjourney',null,'2026-02-28','2026',
 'Midjourney revenue around $500M with headcount reported between 40 and 107',
 'Implied RPE spans $4.7M to $12.5M.',
 500000000,null,'ratio','unverified','Denominator uncertain.',
 5,null,false,null,null,0,null,null,
 true,true,true,null,'speculation',3,true,null,
 'disputed','Same problem as Cursor, smaller range.','press','Multiple outlets','2026-02-28'),

-- ==================== AI-native services roll-ups ====================
('crescendo-gross-margin','crescendo',null,'2026-01-31','2026',
 'Crescendo reports 60-65% gross margin, roughly four times the contact-centre norm',
 'Up to 90% of frontline tickets resolved across 50 languages.',
 null,62.5,'pct','net_pl','Gross margin, self-reported by a private company.',
 5,'Retained as margin.',false,null,null,0,
 'Unaudited. Every operating number in this group is self-reported by a private company with active fundraising.',null,
 true,true,true,null,'speculation',2,true,'Private, fundraising.',
 'needs_primary_source','No audited source exists. Treat the margin figure as a claim, not a measurement.',
 'press','Company statements','2026-01-31'),

('crescendo-per-resolved-ticket','crescendo',null,'2026-01-31','2026',
 'Crescendo charges per resolved ticket rather than per hour — the mechanism, and it is not the AI',
 'A contact centre billing per agent-hour that deploys identical AI capability captures nothing; it just bills fewer hours. Changing the unit of sale from an input the AI destroys to an output the AI produces is what produces the margin.',
 null,null,null,'unit_economics','Pricing structure, not a measured outcome.',
 5,'The single most transferable observation in the corpus.',
 false,null,null,0,null,null,
 true,true,true,'This row is condition 1 stated as a design decision rather than as a constraint.',
 'fact',2,true,null,
 'secondary_only','Company pricing statements.','press','Company statements','2026-01-31'),

('long-lake-100m-ebitda','long-lake',null,'2026-01-31','2024-26',
 'Long Lake reports $100M of EBITDA in under two years',null,
 100000000,100,'usd','net_pl','EBITDA, unaudited, self-reported.',
 5,null,false,null,null,0,
 'Unaudited and unverifiable. Included with the tag it deserves rather than excluded.',null,
 true,true,true,null,'speculation',2,true,'Private company with active fundraising.',
 'needs_primary_source','No independent verification exists today.','press','Company statements','2026-01-31'),

('long-lake-amex-gbt','long-lake',null,'2026-05-31','May 2026',
 'Long Lake announces a $6.3B take-private of Amex GBT, expected to close H2 2026',
 'Amex GBT generated $2.7B of revenue and $182M of operating profit in 2025; the deal was struck around 7x EBITDA. This is evidence of capital access, not of margin transformation.',
 6300000000,6.3,'usd','net_pl','Transaction value.',
 0,'Not a gain claim. It is the date on which this entire group becomes verifiable for the first time.',
 false,null,null,0,
 'The moment a public companys disclosure obligations attach, the roll-up margin thesis becomes testable. Put the close date in your calendar.',null,
 true,true,true,null,'fact',1,false,null,
 'needs_primary_source','Track the merger proxy and, post-close, the first set of segment disclosures. This is the highest-value single verification in the ledger.',
 'sec_filing','Merger announcement','2026-05-31'),

('dwelly-cycle-time','dwelly',null,'2026-01-31','2026',
 'Dwelly reports problem resolution falling from 50 days to 20 days',null,
 null,-30,'time','time','Cycle time. Not a margin claim.',
 2,'Quality and cycle time, with no published financial conversion.',
 false,null,null,0,null,null,
 true,true,true,null,'speculation',2,true,null,
 'needs_primary_source','Ask whether cycle time converted to any revenue or cost effect.','press','Company statements','2026-01-31'),

('titan-msp-38pct','titan-msp',null,'2026-01-31','2026',
 'Titan MSP reports 38% of typical MSP tasks automated',null,
 null,38,'pct','activity','Task-level automation percentage.',
 0,null,false,null,null,0,null,null,
 true,true,true,null,'speculation',2,true,null,
 'needs_primary_source','Task-level automation percentages are the least standardised metric in this document.',
 'press','Company statements','2026-01-31'),

('gc-70-categories-to-10','current-crete',null,'2026-01-31','2025-26',
 'General Catalyst maps about 70 services categories down to the 10 where AI could reach software-like 30-40% margins',
 'They estimate for each category what share of tasks could be automated, recruit founding teams, build the software, prove the automation percentage with pilot clients, and only then acquire.',
 null,null,null,'unverified','A selection method, publicly described. Not an outcome.',
 5,'The most useful disclosure in the group: it is a repeatable screen rather than a result.',
 false,null,null,0,null,null,
 true,true,true,null,'fact',3,true,null,
 'secondary_only','Public remarks by Marc Bhargava. Worth transcribing in full: the screen itself is the transferable asset.',
 'interview','Public remarks','2026-01-31'),

-- ========================== Healthcare ===============================
('tpmg-15791-hours','tpmg-kaiser',null,'2025-06-30','Oct 2023 - Dec 2024',
 'Kaiser Permanente: about 15,791 hours of documentation time saved across 7,260 physicians and 2.5M encounters',
 'Roughly 1,800 eight-hour workdays. After-hours documentation down 1.03 minutes per appointment. 84% reported a positive communication effect.',
 null,15791,'hours','time',
 'Documentation time saved, measured from EHR telemetry. Rigorous, and deliberately not converted to dollars.',
 2,'The freed hour has no mechanism to become money: the schedule is fixed by the appointment book, not by documentation speed.',
 false,null,null,0,null,null,
 false,false,false,'Fails condition 2 structurally. The appointment book is the constraint.',
 'fact',1,false,null,
 'verified_primary','JAMA Network Open. Peer reviewed, largest deployment measured.','peer_reviewed','JAMA Network Open','2025-06-30'),

('mgb-burnout-21pp','mass-general-brigham',null,'2025-06-30','84 days',
 'Mass General Brigham: 21.2 percentage point absolute reduction in burnout prevalence at 84 days',
 'Across 1,400+ clinicians.',
 null,21.2,'pct','quality','Burnout prevalence, measured instrument, absolute change.',
 2,'A real, large, well-measured gain that lands entirely in wellbeing.',
 false,null,null,0,
 'There is no P&L line for burnout. That is the finding, not a failure of the study.',null,
 false,false,false,null,'fact',1,false,null,
 'verified_primary','JAMA Network Open.','peer_reviewed','JAMA Network Open','2025-06-30'),

('sutter-after-hours','sutter-health',null,'2025-09-30','2025',
 'Sutter Health: share of clinicians spending under an hour a week on after-hours notes rises from 14% to 54%',
 'Full attention to patients 58% to 93%. Burnout 42% to 35%.',
 null,40,'pct','quality','Self-reported time and attention measures.',
 2,null,false,null,null,0,null,null,
 false,false,false,null,'fact',1,false,null,
 'verified_primary','JAMA Network Open.','peer_reviewed','JAMA Network Open','2025-09-30'),

('uchicago-ehr-time','uchicago-medicine',null,'2025-09-30','2025',
 'UChicago Medicine: 8.5% less total EHR time and over 15% less note-composition time, matched-control design',null,
 null,8.5,'pct','time','EHR telemetry with a matched control group.',
 2,null,false,null,null,0,null,null,
 false,false,false,null,'fact',1,false,null,
 'verified_primary','JAMA Network Open.','peer_reviewed','JAMA Network Open','2025-09-30'),

('reid-wrvu-4pct','reid-health',null,'2025-12-31','2025',
 'Reid Health: 4% increase in work RVUs per patient encounter — one of the few revenue-side conversions documented anywhere',
 'Across 300 clinicians. They converted it because coding and billing intensity is a revenue lever they could actually pull.',
 null,4,'pct','net_pl','Work RVUs per encounter. A billable unit.',
 5,'The exception that proves the rule. The freed hour only becomes money where there is a mechanism to sell it.',
 false,null,null,0,null,null,
 true,true,true,'The only healthcare row in the corpus that passes condition 2.',
 'fact',2,false,null,
 'needs_primary_source','Find the underlying case study and whether the wRVU lift persisted beyond the measurement window.',
 'vendor_report','Health system case study','2025-12-31'),

('phti-no-financial-roi','phti',null,'2025-03-31','Mar 2025',
 'Ambient scribes reduce burnout and cognitive load but have not demonstrated a financial return on investment',
 'Taskforce included CommonSpirit, Intermountain, Mass General Brigham, MultiCare, Ochsner, Providence, UC San Diego and Yale New Haven. Evidence for time savings was called limited and mixed, with a warning that adoption may add to overall costs of care.',
 null,0,'usd','net_pl','Financial return on investment, assessed by an independent taskforce.',
 2,'The verdict on the money for the whole of destination 2.',
 false,null,null,0,null,
 'Spend of $100-600 per provider per month against no demonstrated financial return.',
 false,false,false,null,'fact',1,false,null,
 'verified_primary','PHTI AI taskforce report, March 2025. Independent of vendors, which is what makes it load-bearing.',
 'peer_reviewed','Peterson Health Technology Institute','2025-03-31'),

('ucla-scribe-rct','ucla-health',null,'2026-01-31','ongoing',
 'UCLA runs a three-arm randomised controlled trial of ambient scribes across 238 physicians and 14 specialties',
 'DAX versus Nabla versus usual care. A genuinely rare design in this space.',
 null,238,'ratio','quality','Randomised controlled trial. Results pending at time of coding.',
 0,'Cannot be coded until results publish.',false,null,null,0,null,null,
 false,false,false,null,'unknown',1,false,null,
 'needs_primary_source','ClinicalTrials.gov NCT06792890. Set a reminder: this is the strongest design in the healthcare set and the results will move several rows.',
 'peer_reviewed','ClinicalTrials.gov','2026-01-31'),

('ambient-adoption-two-thirds','phti',null,'2026-01-31','Jun 2025',
 'Nearly two-thirds of US hospitals on Epic had adopted ambient AI documentation by June 2025',
 'Around 60 ambient scribe products on the market, at $100-600 per provider per month.',
 null,66,'pct','activity','Adoption rate.',
 2,'One of the fastest technology adoptions in healthcare history, into a destination with no demonstrated financial return.',
 false,null,null,0,null,null,
 false,false,false,null,'fact',1,false,null,
 'verified_primary','American Journal of Managed Care, January 2026.','peer_reviewed','AJMC','2026-01-31'),

-- ====================== Research populations =========================
('spi-utilization-664','spi-research-population',null,'2026-01-31','FY2025',
 'Professional services: GenAI in 27.1% of projects, up 40% year over year, while billable utilisation falls to 66.4%, the lowest in survey history',
 'EBITDA 9.9% against a five-year average of 13.8%. Revenue per consultant $210K. Project margin 37.7%. SPI target utilisation is 75%.',
 null,66.4,'pct','net_pl','Billable utilisation and EBITDA across 509 benchmarked organisations.',
 1,'A third of capacity idle, and AI making the remaining two-thirds faster. The freed hours have nowhere to go, and because the billing unit is the hour, faster delivery reduces revenue directly.',
 false,null,null,0,
 'The clearest sector-level instance of the volume-constraint hypothesis in the whole corpus.',
 'Utilisation fell to an all-time low in the same year AI use in delivery rose 40%.',
 false,false,true,'Fails conditions 1 and 2 simultaneously.',
 'strong',2,false,null,
 'secondary_only','SPI Research 2026 Professional Services Maturity Benchmark. Get the actual report; the utilisation series matters more than the headline.',
 'industry_survey','SPI Research','2026-01-31'),

('denmark-precise-null','denmark-admin-data',null,'2025-05-31','2023-24',
 'Denmark, 25,000 workers across 7,000 workplaces: 2.8% of hours saved, and a precise null on earnings and hours',
 'Only 3-7% of the productivity gain passed through to pay. The null rules out effects larger than about 2%.',
 null,2.8,'pct','time','Administrative payroll data. Measures the firms realised hours and earnings, not a treated worker on a treated task.',
 1,'Absorbed as worker slack. Nothing changes financially.',
 false,null,null,0,
 'The gap between this and the RCT results is the entire phenomenon. Different objects, both correctly measured.',null,
 null,false,null,null,'fact',1,false,null,
 'verified_primary','Humlum and Vestergaard, NBER w33777.','peer_reviewed','NBER working paper','2025-05-31'),

('brynjolfsson-14-34','brynjolfsson-rct',null,'2023-04-30','2023',
 'Customer support RCT: +14% issues resolved per hour on average, +34% for novices, minimal effect for experienced agents',
 'For the most experienced agents, chats per hour were positive but not significant, and there were small but statistically significant negative effects on call quality and customer satisfaction.',
 null,14,'pct','time','Issues resolved per hour, staggered rollout across 5,179 agents.',
 0,'A treated worker on a treated task. Does not tell you where the gain lands in the firm.',
 false,null,null,0,
 'AI raises the floor, not the ceiling. The firms with the most to gain are the least likely to have the measurement apparatus to detect it, the capital to buy the tool, or the management capacity to redesign the workflow.',null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Brynjolfsson, Li and Raymond, NBER w31161.','peer_reviewed','NBER working paper','2023-04-30'),

('canaries-16pct','stanford-canaries',null,'2026-02-28','2022-26',
 'Employment for 22-25 year olds in AI-exposed occupations falls 16% in relative terms',
 'About 20% for young software developers since late 2022, with experienced workers stable. Declines concentrate where AI automates; employment grows where AI augments.',
 null,-16,'pct','headcount','Firm-level payroll data on the hiring margin, not the firing or wage margin.',
 0,'Reconciles with the Danish null: adjustment happens through hiring, which administrative hours data on incumbents will not detect.',
 false,null,null,0,null,null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Stanford Digital Economy Lab, February 2026 update.','peer_reviewed','Stanford Digital Economy Lab','2026-02-09'),

('mckinsey-39-and-6','mckinsey-state-of-ai',null,'2025-11-05','2025',
 '39% of firms attribute any EBIT impact to AI, most of them under 5%; about 6% qualify as high performers',
 '1,993 respondents across 105 nations. 88% report regular AI use in at least one function. 7% report AI fully scaled. In any given function, no more than 10% are scaling agents. High performers are 109 of 1,993.',
 null,39,'pct','unverified',
 'Executive belief, not measurement. What share of enterprise EBIT is attributable to AI is not a question a survey respondent has the instrumentation to answer.',
 0,'The headline gap that the rest of this ledger exists to decompose.',
 false,null,null,0,
 'Read as belief rather than measurement. That reframing changes what the 39% is evidence of.',null,
 null,null,null,null,'strong',2,true,'Consulting firm selling AI transformation.',
 'secondary_only','McKinsey State of AI 2025. The relative-weights analysis on 31 variables is the useful part, not the headline.',
 'industry_survey','McKinsey QuantumBlack','2025-11-05'),

('nanda-95pct','mit-nanda',null,'2025-07-31','Jan-Jun 2025',
 'The widely quoted 95%: only 5% of task-specific GenAI pilots reach sustained impact',
 'From 300+ publicly disclosed initiatives, 52 structured interviews and 153 survey responses. General-purpose LLMs fare far better at 40%. The reports own limitations section calls the figures directionally accurate based on individual interviews rather than official company reporting, and says a six-month window may understate success.',
 null,95,'pct','unverified',
 'An interview-derived estimate. It is quoted everywhere as though it were a measurement. It is not.',
 0,'Directional evidence only.',false,null,null,0,
 'This row exists to stop the 95% re-entering an argument as a fact.',null,
 null,null,null,null,'inference',2,false,null,
 'secondary_only','Read the limitations section, not the headline. A 52-organisation interview sample is not a representative survey.',
 'vendor_report','MIT Project NANDA','2025-07-31'),

('nanda-buy-vs-build','mit-nanda',null,'2025-07-31','2025',
 'External partnerships reach deployment about 67% of the time versus about 33% for internal builds',
 'Employee usage rates are nearly double for externally built tools. 66% of observed deployments were buy, 33% build.',
 null,67,'pct','activity','Deployment success rate by sourcing mode.',
 0,'If partnerships deploy at twice the rate and the median enterprise builds internally, a meaningful share of the 95% failure is a make-or-buy error rather than a technology limitation.',
 false,null,null,0,null,null,
 null,null,null,null,'inference',2,false,null,
 'secondary_only','NANDA flags the confound honestly: firms choosing partnerships may differ in risk tolerance and procurement sophistication.',
 'vendor_report','MIT Project NANDA','2025-07-31'),

('nanda-budget-misallocation','mit-nanda',null,'2025-07-31','2025',
 '50-70% of GenAI budget goes to sales and marketing because outcomes there are easy to attribute, not because ROI is highest',
 'Back office delivered the larger documented savings and gets funded less.',
 null,60,'pct','activity','Budget allocation by function.',
 0,'Measuring where measurement is easy rather than where value is. One of six named measurement pathologies.',
 false,null,null,0,null,null,
 null,null,null,null,'strong',2,false,null,
 'secondary_only','NANDA states the causal claim explicitly, which is unusual and worth quoting accurately.',
 'vendor_report','MIT Project NANDA','2025-07-31'),

('nanda-enterprise-paradox','mit-nanda',null,'2025-07-31','2025',
 'Enterprises lead in pilot count and have the lowest pilot-to-scale conversion: nine months versus 90 days for mid-market',
 null,
 null,270,'time','time','Days from pilot to full implementation.',
 0,'Condition 3, permission to act, measured in days.',false,null,null,0,null,null,
 null,null,false,'This is the cleanest available proxy for permission-to-act friction.',
 'strong',2,false,null,
 'secondary_only','NANDA. Not contradictory with McKinsey: large firms scale more programs in absolute terms and convert a lower share.',
 'vendor_report','MIT Project NANDA','2025-07-31'),

('census-btos-198','census-btos',null,'2026-05-03','May 2026',
 'National AI use rate 19.8%; under 20% for firms with four or fewer employees, and no significant change since December 2025',
 'Firms with 250+ employees: 37%. 100-249: 32%. AI use rose among firms with 20+ employees and did not move among firms below 20.',
 null,19.8,'pct','activity','Firm-level AI use, from a roughly 1.2M business sample, biweekly.',
 0,'Any framework treating AI implementation as a project with a budget and a measurement plan is describing roughly the top 5% of firms by employment.',
 false,null,null,0,null,null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','US Census Business Trends and Outlook Survey, AI supplement.','industry_survey','US Census Bureau','2026-05-03'),

('census-function-vs-task','census-btos',null,'2026-04-30','Nov 2025 - Jan 2026',
 'Giving workers AI tools does not reduce headcount. Restructuring functions around AI does.',
 '18% of firms used AI in a business function, 32% employment-weighted. 57% of adopters integrate in three or fewer functions. 66% use AI solely to augment. AI-related employment decreases occurred in only 2% of firms. Functional breadth and operational investment associate with employment decreases; worker-task integration shows no significant link once function-level integration and operational investment are controlled for.',
 null,2,'pct','headcount','Linked administrative microdata with regression controls.',
 1,'Almost all adoption is the first kind. This is the mechanism behind the whole ledger.',
 false,null,null,0,
 'The single most decision-relevant finding in the research set, and it comes with a linked-administrative-data pedigree.',null,
 null,null,null,null,'fact',1,false,null,
 'verified_primary','Bonney, Breaux, Dinlersoz, Foster, Haltiwanger and Pande, Census CES-WP-26-25.',
 'peer_reviewed','US Census Bureau working paper','2026-04-30'),

('census-shadow-ai','census-btos',null,'2026-04-30','2026',
 'Worker AI use occurs without firm-level adoption, and firm adoption occurs without worker use',
 'MIT NANDA found 40% of companies bought an LLM subscription while workers at over 90% used personal tools for work.',
 null,90,'pct','activity','Divergence between firm-level and worker-level adoption.',
 1,'A share of realised AI productivity is invisible to the firm because the firm did not buy it, does not know it is happening, and cannot measure it. Unmeasured but not zero.',
 false,null,null,0,null,null,
 null,null,null,null,'inference',1,false,null,
 'verified_primary','Census CES-WP-26-25 plus NANDA.','peer_reviewed','US Census Bureau working paper','2026-04-30'),

('thomson-reuters-80pct','thomson-reuters',null,'2026-01-31','2026',
 'Over 80% of senior corporate counsel do not require their outside firms to use AI',
 'And 27% of North American law firms have non-traditional service divisions or ALSP partnerships, against 76% across UK, Europe and Australia.',
 null,80,'pct','activity','Survey of senior corporate counsel.',
 0,'The savings are not yet being demanded by clients. That window is a specific, time-limited arbitrage, and firms billing hourly cannot exploit it anyway because the hour is what shrinks.',
 false,null,null,0,
 'The moment procurement starts asking why the bill is the same, the arbitrage ends. Firms that convert to fixed-fee or outcome pricing before that happens keep the margin.',null,
 false,false,true,null,'fact',2,false,null,
 'secondary_only','Thomson Reuters 2026 State of the Legal Market. Watch the 27% figure annually: it is the leading indicator.',
 'industry_survey','Thomson Reuters','2026-01-31'),

('mckinsey-high-performer-traits','mckinsey-state-of-ai',null,'2025-11-05','2025',
 'What separates the 6%: fundamental workflow redesign, transformative intent, growth objectives, defined human-validation processes, senior ownership, budget concentration, agent scaling',
 'Workflow redesign showed one of the strongest contributions of any of 31 variables tested, with high performers about 3x more likely. Over a third of high performers commit more than 20% of digital budget to AI.',
 null,6,'pct','activity','Relative weights analysis across 31 variables.',
 5,'Meeting two of three conditions produces measurable operational improvement and no EBIT effect. That describes most of the 88%. Meeting all three describes roughly the 6%.',
 false,null,null,0,null,null,
 true,true,true,null,'strong',2,true,'Consulting firm.',
 'secondary_only','McKinsey State of AI 2025, relative weights section. Cross-validates independently with NANDAs interview coding.',
 'industry_survey','McKinsey QuantumBlack','2025-11-05')

)
insert into claims (
  ref, company_id, counterparty_id, claim_date, period_label, headline, claim_detail,
  claimed_amount_usd, claimed_value, claimed_unit, measurement_basis, measurement_definition,
  destination, destination_rationale, counterparty_absorbed, transfer_amount_usd, counterparty_note,
  traceable_to_pl_usd, reconciliation_note, observed_counter_move,
  cond_billing_unit_survives, cond_demand_sink, cond_permission_to_act, conditions_note,
  epistemic_tag, evidence_tier, conflict_of_interest, coi_note,
  verification_status, verify_hint, source_type, source_name, source_date
)
select
  s.ref, co.id, cp.id, s.claim_date, s.period_label, s.headline, s.claim_detail,
  s.claimed_amount_usd, s.claimed_value, s.claimed_unit, s.measurement_basis, s.measurement_definition,
  s.destination, s.destination_rationale, s.counterparty_absorbed, s.transfer_amount_usd, s.counterparty_note,
  s.traceable_to_pl_usd, s.reconciliation_note, s.observed_counter_move,
  s.cond_bu, s.cond_ds, s.cond_pa, s.conditions_note,
  s.epistemic_tag, s.evidence_tier, s.conflict_of_interest, s.coi_note,
  s.verification_status, s.verify_hint, s.source_type, s.source_name, s.source_date
from src s
join companies co on co.slug = s.company_slug
left join companies cp on cp.slug = s.counterparty_slug
on conflict (ref) do update set
  headline               = excluded.headline,
  claim_detail           = excluded.claim_detail,
  claimed_amount_usd     = excluded.claimed_amount_usd,
  claimed_value          = excluded.claimed_value,
  claimed_unit           = excluded.claimed_unit,
  measurement_basis      = excluded.measurement_basis,
  measurement_definition = excluded.measurement_definition,
  destination            = excluded.destination,
  destination_rationale  = excluded.destination_rationale,
  counterparty_absorbed  = excluded.counterparty_absorbed,
  counterparty_id        = excluded.counterparty_id,
  transfer_amount_usd    = excluded.transfer_amount_usd,
  counterparty_note      = excluded.counterparty_note,
  traceable_to_pl_usd    = excluded.traceable_to_pl_usd,
  reconciliation_note    = excluded.reconciliation_note,
  observed_counter_move  = excluded.observed_counter_move,
  cond_billing_unit_survives = excluded.cond_billing_unit_survives,
  cond_demand_sink           = excluded.cond_demand_sink,
  cond_permission_to_act     = excluded.cond_permission_to_act,
  conditions_note        = excluded.conditions_note,
  epistemic_tag          = excluded.epistemic_tag,
  evidence_tier          = excluded.evidence_tier,
  conflict_of_interest   = excluded.conflict_of_interest,
  coi_note               = excluded.coi_note,
  verification_status    = excluded.verification_status,
  verify_hint            = excluded.verify_hint,
  source_type            = excluded.source_type,
  source_name            = excluded.source_name,
  source_date            = excluded.source_date;

-- sanity check: should print 81
select count(*) as claims_loaded from claims;

-- =====================================================================
-- Row kinds.
--
-- Everything defaults to 'gain_claim'. The rows below are not claims that
-- AI produced a gain, and summing them with the ones that are would make
-- the headline reconciliation figure meaningless. Kept as an explicit,
-- readable list rather than folded into the tuples above, because these
-- are judgment calls and they should be easy to argue with.
-- =====================================================================

-- Observations that contradict or bound a gain claim.
update claims set claim_kind = 'counter_evidence' where ref in (
  'ibm-headcount-rose',
  'salesforce-margin-did-not-expand',
  'klarna-quality-reversal',
  'cba-reverses-cuts',
  'duolingo-ai-first-walkback',
  'accenture-own-economics',
  'teleperformance-fy2025-loss',
  'teleperformance-q1-2026',
  'concentrix-guidance-cut-130m',
  'concentrix-ceo-attribution',
  'chegg-revenue-collapse',
  'chegg-value-destruction',
  'atlassian-seat-decline',
  'software-multiple-compression',
  'isg-bpo-acv-minus-14',
  'phti-no-financial-roi'
);

-- Spend, transaction values, adoption rates, methods, and figures that
-- cannot be computed. Real and useful; not gains.
update claims set claim_kind = 'context' where ref in (
  'servicenow-ai-acv-1b',
  'salesforce-agentforce-arr',
  'jpm-ai-spend-2b',
  'accenture-ai-bookings-11-5b',
  'long-lake-amex-gbt',
  'ambient-adoption-two-thirds',
  'gc-70-categories-to-10',
  'verizon-opex-5b-target',
  'verizon-ebitda-389',
  'ucla-scribe-rct',
  'cursor-rpe-unusable',
  'midjourney-rpe-range',
  'amazon-corporate-reductions-2025',
  'shopify-ai-hiring-gate',
  'titan-msp-38pct'
);

-- Prices per unit of output. These are the pass-through mechanism, not a
-- saving anyone booked.
update claims set claim_kind = 'pricing' where ref in (
  'salesforce-agentforce-2usd',
  'intercom-fin-099',
  'hubspot-050-repricing',
  'zendesk-verified-resolution',
  'per-seat-pricing-collapse',
  'crescendo-per-resolved-ticket'
);

-- Population-level research. The counter-weight to every firm-level claim
-- in the table, and the reason they live in the same table.
update claims set claim_kind = 'research_finding' where ref in (
  'spi-utilization-664',
  'denmark-precise-null',
  'brynjolfsson-14-34',
  'canaries-16pct',
  'mckinsey-39-and-6',
  'mckinsey-high-performer-traits',
  'nanda-95pct',
  'nanda-buy-vs-build',
  'nanda-budget-misallocation',
  'nanda-enterprise-paradox',
  'nanda-bpo-elimination-2-10m',
  'census-btos-198',
  'census-function-vs-task',
  'census-shadow-ai',
  'thomson-reuters-80pct'
);

select claim_kind, count(*) from claims group by 1 order by 2 desc;
