import type { LedgerRow } from '../src/lib/types';

/** A row with every field present, so tests never accidentally rely on
 *  a field being undefined. Override only what the test is about. */
export function row(patch: Partial<LedgerRow> = {}): LedgerRow {
  return {
    id: patch.ref ?? Math.random().toString(36).slice(2),
    ref: 'test-row',
    claim_date: '2025-06-30',
    period_label: 'Q2 2025',
    headline: 'A company reports a saving',
    claim_detail: null,
    claim_kind: 'gain_claim',
    claimed_amount_usd: null,
    claimed_value: null,
    claimed_unit: null,
    measurement_basis: 'net_pl',
    measurement_definition: null,
    destination: 0,
    destination_rationale: null,
    counterparty_absorbed: false,
    counterparty_note: null,
    transfer_amount_usd: null,
    traceable_to_pl_usd: 0,
    unreconciled_usd: 0,
    reconciliation_note: null,
    observed_counter_move: null,
    cond_billing_unit_survives: null,
    cond_demand_sink: null,
    cond_permission_to_act: null,
    conditions_note: null,
    epistemic_tag: 'fact',
    evidence_tier: 1,
    conflict_of_interest: false,
    coi_note: null,
    verification_status: 'verified_primary',
    verify_hint: null,
    source_type: 'sec_filing',
    source_name: 'Form 10-Q',
    source_url: null,
    source_date: '2025-07-15',
    company_name: 'Test Co',
    company_slug: 'test-co',
    company_ticker: 'TST',
    sector: 'Testing',
    group_code: 'D',
    group_label: 'Large incumbent',
    company_is_public: true,
    counterparty_name: null,
    counterparty_slug: null,
    margin_delta_1q_bps: null,
    margin_delta_4q_bps: null,
    margin_baseline: null,
    margin_t4q: null,
    price_delta_4q: null,
    ...patch,
  };
}

/** A small but structurally complete corpus mirroring the real one:
 *  a slack claim, a margin claim, a transfer, and a research row. */
export const CORPUS: LedgerRow[] = [
  row({
    ref: 'ibm-slack', company_slug: 'ibm', company_name: 'IBM', group_code: 'C',
    claimed_amount_usd: 3_500_000_000, traceable_to_pl_usd: 0, unreconciled_usd: 3_500_000_000,
    destination: 1, measurement_basis: 'gross_capacity', claim_date: '2024-12-31',
    destination_rationale: 'Capacity was redeployed into engineering, sales and marketing.',
    observed_counter_move: 'Total headcount rose over the same period.',
    cond_billing_unit_survives: true, cond_demand_sink: true, cond_permission_to_act: true,
    evidence_tier: 2, conflict_of_interest: true, verification_status: 'secondary_only',
  }),
  row({
    ref: 'klarna-marketing', company_slug: 'klarna', company_name: 'Klarna', group_code: 'D',
    claimed_amount_usd: 28_000_000, traceable_to_pl_usd: 28_000_000, unreconciled_usd: 0,
    destination: 5, measurement_basis: 'net_pl', claim_date: '2025-11-30',
    margin_delta_4q_bps: 45,
    cond_billing_unit_survives: true, cond_demand_sink: true, cond_permission_to_act: true,
  }),
  row({
    ref: 'klarna-60m', company_slug: 'klarna', company_name: 'Klarna', group_code: 'D',
    claimed_amount_usd: 60_000_000, traceable_to_pl_usd: 0, unreconciled_usd: 60_000_000,
    destination: 1, measurement_basis: 'gross_capacity', claim_date: '2025-11-30',
    observed_counter_move: 'Customer service cost rose 19% year over year.',
    cond_billing_unit_survives: false, cond_demand_sink: false, cond_permission_to_act: false,
  }),
  row({
    ref: 'nanda-bpo', company_slug: 'mit-nanda', company_name: 'MIT NANDA', group_code: 'R',
    claim_kind: 'research_finding', destination: 3, counterparty_absorbed: true,
    counterparty_slug: 'concentrix', counterparty_name: 'Concentrix',
    transfer_amount_usd: 130_000_000, claim_date: '2025-07-31',
    measurement_basis: 'net_pl', claimed_amount_usd: null,
  }),
  row({
    ref: 'chegg-market-cap', company_slug: 'chegg', company_name: 'Chegg', group_code: 'J',
    claim_kind: 'counter_evidence', claimed_amount_usd: 2_000_000_000_000,
    traceable_to_pl_usd: 0, unreconciled_usd: 2_000_000_000_000, destination: 0,
    claim_date: '2026-07-31',
  }),
  row({
    ref: 'cursor-unusable', company_slug: 'anysphere', company_name: 'Anysphere', group_code: 'A',
    claim_kind: 'context', measurement_basis: 'unverified', verification_status: 'disputed',
    destination: 0, claim_date: '2026-05-31',
    verify_hint: 'Only a company-confirmed headcount resolves this.',
  }),
];
